import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import AppWalletProvider from "@/components/AppWalletProvider";
import FloatingNavbar from "@/components/FloatingNavbar";

type ToasterProps = React.ComponentProps<typeof Toaster>;
const toastOptions: ToasterProps = {
  theme: "dark",
  richColors: true,
  closeButton: true,
  pauseWhenPageIsHidden: true,
};
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "GrooveQ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full bg-black`}
      >
        <AppWalletProvider>
          <Toaster {...toastOptions} />
          <FloatingNavbar />
          {children}
        </AppWalletProvider>
      </body>
    </html>
  );
}